# Generated by Django 5.1.3 on 2026-04-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('recommended_timeframe', models.CharField(help_text="e.g., 'At Birth', '6 Weeks'", max_length=255)),
                ('deadline_days', models.IntegerField(blank=True, help_text='Maximum days after birth this vaccine can be given', null=True)),
            ],
        ),
    ]
