# Generated by Django 5.1.3 on 2026-04-26 04:19

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('login_id', models.CharField(help_text='Auto-generated: NAME-UUID (e.g. JOHN-A1B2)', max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be 9–15 digits, optionally prefixed with +.', regex='^\\+?1?\\d{9,15}$')])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('is_verified', models.BooleanField(default=False, help_text='False until the user completes Step 2 activation.')),
                ('user_type', models.CharField(choices=[('normal', 'Normal User'), ('medical', 'Medical Personnel')], max_length=10)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('special_conditions', models.TextField(blank=True, help_text='Comma-separated list of special health conditions')),
                ('region', models.CharField(blank=True, max_length=255)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='+', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='+', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Normal User',
                'verbose_name_plural': 'Normal Users',
                'db_table': 'normal_user',
                'indexes': [models.Index(fields=['email'], name='normal_user_email_7819da_idx'), models.Index(fields=['login_id'], name='normal_user_login_i_43b485_idx'), models.Index(fields=['status'], name='normal_user_status_0a42a3_idx')],
            },
        ),
        migrations.CreateModel(
            name='MedicalPersonnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('login_id', models.CharField(help_text='Auto-generated: NAME-UUID (e.g. JOHN-A1B2)', max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be 9–15 digits, optionally prefixed with +.', regex='^\\+?1?\\d{9,15}$')])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('is_verified', models.BooleanField(default=False, help_text='False until the user completes Step 2 activation.')),
                ('user_type', models.CharField(choices=[('normal', 'Normal User'), ('medical', 'Medical Personnel')], max_length=10)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='+', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='+', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Medical Personnel',
                'verbose_name_plural': 'Medical Personnel',
                'db_table': 'medical_personnel',
                'indexes': [models.Index(fields=['email'], name='medical_per_email_dba71f_idx'), models.Index(fields=['login_id'], name='medical_per_login_i_030ef6_idx'), models.Index(fields=['status'], name='medical_per_status_3d270a_idx')],
            },
        ),
    ]
