# Generated by Django 6.0.4 on 2026-04-25 18:31

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
                'db_table': 'region',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Email Verification Token',
                'verbose_name_plural': 'Email Verification Tokens',
                'db_table': 'email_verification_token',
                'indexes': [models.Index(fields=['email', 'is_used'], name='email_verif_email_c6a8dd_idx'), models.Index(fields=['token'], name='email_verif_token_a0fc48_idx')],
            },
        ),
        migrations.CreateModel(
            name='MedicalPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('login_id', models.CharField(help_text='6-8 character login identifier (auto-generated)', max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be between 9 and 15 digits', regex='^\\+?1?\\d{9,15}$')])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('is_verified', models.BooleanField(default=False, help_text='Email verification status')),
                ('user_type', models.CharField(choices=[('normal', 'Normal User'), ('medical', 'Medical Personnel')], max_length=10)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Medical Personnel',
                'verbose_name_plural': 'Medical Personnel',
                'db_table': 'medical_personnel',
                'indexes': [models.Index(fields=['email'], name='medical_per_email_dba71f_idx'), models.Index(fields=['login_id'], name='medical_per_login_i_030ef6_idx'), models.Index(fields=['status'], name='medical_per_status_3d270a_idx')],
            },
        ),
        migrations.CreateModel(
            name='NormalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('login_id', models.CharField(help_text='6-8 character login identifier (auto-generated)', max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be between 9 and 15 digits', regex='^\\+?1?\\d{9,15}$')])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('is_verified', models.BooleanField(default=False, help_text='Email verification status')),
                ('user_type', models.CharField(choices=[('normal', 'Normal User'), ('medical', 'Medical Personnel')], max_length=10)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, help_text="User's date of birth", null=True)),
                ('special_conditions', models.TextField(blank=True, help_text='Comma-separated list of special health conditions')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='normal_users', to='user.region')),
            ],
            options={
                'verbose_name': 'Normal User',
                'verbose_name_plural': 'Normal Users',
                'db_table': 'normal_user',
                'indexes': [models.Index(fields=['email'], name='normal_user_email_7819da_idx'), models.Index(fields=['login_id'], name='normal_user_login_i_43b485_idx'), models.Index(fields=['status'], name='normal_user_status_0a42a3_idx')],
            },
        ),
    ]
