# Generated by Django 6.0.4 on 2026-04-25 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normaluser',
            name='region',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
