# Generated by Django 6.0.4 on 2026-04-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='normaluser',
            name='region',
            field=models.CharField(blank=True, help_text='Region identifier (will be linked to Region model later)', max_length=255),
        ),
    ]
