# Generated by Django 6.0.4 on 2026-04-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_medicalpersonnel_id_alter_normaluser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalpersonnel',
            name='user_type',
            field=models.CharField(choices=[('normal', 'Normal User'), ('medical', 'Medical Personnel')], default='normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='user_type',
            field=models.CharField(choices=[('normal', 'Normal User'), ('medical', 'Medical Personnel')], default='normal', max_length=10),
        ),
    ]
