# Generated by Django 6.0.4 on 2026-04-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0003_alter_region_to_charfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='normaluser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='normaluser_groups', to='auth.group'),
        ),
        migrations.AddField(
            model_name='normaluser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='normaluser_user_permissions', to='auth.permission'),
        ),
        migrations.AddField(
            model_name='medicalpersonnel',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='medicalpersonnel_groups', to='auth.group'),
        ),
        migrations.AddField(
            model_name='medicalpersonnel',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='medicalpersonnel_user_permissions', to='auth.permission'),
        ),
    ]
