# Generated by Django 6.0.4 on 2026-04-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0004_add_permissions_mixin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalpersonnel',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='+', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='medicalpersonnel',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='+', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='+', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='+', to='auth.permission'),
        ),
    ]
