# Generated by Django 6.0.4 on 2026-04-26 02:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_email_unique_constraint'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='emailverificationtoken',
            name='email_verif_email_c6a8dd_idx',
        ),
        migrations.RemoveIndex(
            model_name='emailverificationtoken',
            name='email_verif_token_a0fc48_idx',
        ),
        migrations.DeleteModel(
            name='EmailVerificationToken',
        ),
        migrations.AlterField(
            model_name='medicalpersonnel',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='False until the user completes Step 2 activation.'),
        ),
        migrations.AlterField(
            model_name='medicalpersonnel',
            name='login_id',
            field=models.CharField(help_text='Auto-generated: NAME-UUID (e.g. JOHN-A1B2)', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='medicalpersonnel',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be 9–15 digits, optionally prefixed with +.', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='False until the user completes Step 2 activation.'),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='login_id',
            field=models.CharField(help_text='Auto-generated: NAME-UUID (e.g. JOHN-A1B2)', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be 9–15 digits, optionally prefixed with +.', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
