# Generated by Django 6.0.4 on 2026-04-26 14:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_alter_medicalpersonnel_id_alter_normaluser_id'),
        ('visualisation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccination_name', models.CharField(max_length=100)),
                ('vaccination_dosage', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, verbose_name='Name of the Event')),
                ('event_status', models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('ENDED', 'ENDED')], default='NOT_STARTED', max_length=20, verbose_name='Event Status')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Event Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_phone_number', models.CharField(max_length=100, verbose_name='Contact Phone Number')),
                ('event_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='visualisation.district', verbose_name='Event Location')),
                ('organized_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.medicalpersonnel', verbose_name='Organized By')),
            ],
            options={
                'verbose_name': 'Event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event', verbose_name='Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Event User',
                'ordering': ['-event__created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventVaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event', verbose_name='Event')),
                ('vaccination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.vaccination', verbose_name='Vaccination')),
            ],
            options={
                'verbose_name': 'Event Vaccination',
                'ordering': ['-event__created_at'],
            },
        ),
    ]
