# Generated by Django 5.1.3 on 2026-04-26 06:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('province', models.CharField(max_length=100)),
                ('imr_classification', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('population', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'ordering': ['province', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IndividualVaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=100)),
                ('dose_number', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('date_administered', models.DateField(blank=True, null=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('scheduled', 'Scheduled'), ('missed', 'Missed')], default='scheduled', max_length=20)),
                ('administered_by', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='visualisation.district')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_date', 'vaccine_name'],
                'unique_together': {('user', 'vaccine_name', 'dose_number')},
            },
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('bcg', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('dpt_1', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('dpt_2', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('dpt_3', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('dpt_1b', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('dpt5_2b', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('penta_1', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('penta_2', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('penta_3', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('opv_0', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('opv_1', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('opv_2', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('opv_3', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('opv_b', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('hep_b0', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('hep_b1', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('hep_b2', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('hep_b3', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('meas_1', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('meas_2', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('mmr_v', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('je_1', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('je_16m', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('tt_10', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('tt_16', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_records', to='visualisation.district')),
            ],
            options={
                'ordering': ['-year', 'district__name'],
                'unique_together': {('district', 'year')},
            },
        ),
    ]
