# integrations/calendar.py
# Purpose: Books a doctor appointment via Google Calendar
# when patient risk tier is MEDIUM.
# Uses credentials from creds_verification.py — no duplicate auth logic.
# The event is added to the primary calendar and the doctor
# receives an email invite automatically from Google.

import sys
import os

from datetime import datetime, timedelta, timezone
# datetime: for creating start and end times
# timedelta: for adding hours to current time
# timezone: for UTC timezone (Google Calendar requires timezone)

# Find the absolute path of the directory containing 'integrations'
# This works whether you are in 'src' or 'integrations'
current_dir = os.path.dirname(os.path.abspath(__file__))
parent_dir = os.path.dirname(current_dir)

if parent_dir not in sys.path:
    sys.path.append(parent_dir)

from integrations.creds_verification import get_google_services
# Import our shared credential handler
# This handles all OAuth logic — calendar.py just uses the service

def book_appointment(doctor_email, patient_email, patient_name, risk_summary):
    """
    Creates a Google Calendar event for the patient's doctor appointment.
    Called from pages/03_results.py when risk tier is MEDIUM.

    doctor_email: string — doctor's email from patient profile
    patient_name: string — patient's full name
    risk_summary: string — e.g. "MEDIUM risk — Ear Infection"
    Returns: created event dict or None if booking failed
    """
    # ── GET AUTHENTICATED GOOGLE SERVICES ────────────────────────────
    services = get_google_services()

    if not services:
        print("[calendar] Could not get Google services — appointment not booked")
        return None

    # Get the calendar service client
    calendar_service = services["calendar"]

    # ── BUILD EVENT TIMES ─────────────────────────────────────────────
    # Schedule appointment 2 hours from now as a default
    # In a real app this would use a proper scheduling system
    # Using UTC timezone — Google Calendar requires timezone info
    now_utc = datetime.now(timezone.utc)
    start_time = now_utc + timedelta(hours=2)
    end_time = start_time + timedelta(hours=1)  # 1 hour appointment

    # Google Calendar requires ISO format with timezone
    # e.g. "2026-04-25T14:30:00+00:00"
    start_iso = start_time.isoformat()
    end_iso = end_time.isoformat()

    # ── BUILD EVENT OBJECT ────────────────────────────────────────────
    event = {
        # Event title shown in the calendar
        "summary": f"AI Triage Appointment — {patient_name} ({risk_summary})",

        # Event description with clinical context
        "description": (
            f"This appointment was automatically scheduled by the AI Triage app.\n\n"
            f"Patient: {patient_name}\n"
            f"Risk Assessment: {risk_summary}\n\n"
            f"Please review the triage summary sent to your email before this appointment.\n\n"
            f"DISCLAIMER: This was generated by an AI triage assistant and requires clinical review."
        ),

        # Start and end times with timezone
        "start": {
            "dateTime": start_iso,
            "timeZone": "UTC"
        },
        "end": {
            "dateTime": end_iso,
            "timeZone": "UTC"
        },

        # Attendees — Google Calendar automatically sends email invite
        "attendees": [
            {"email": doctor_email},
            {"email": patient_email}
        ],

        # Send email notifications to all attendees
        "reminders": {
            "useDefault": False,
            "overrides": [
                # Email reminder 1 hour before
                {"method": "email", "minutes": 60},
                # Popup reminder 15 minutes before
                {"method": "popup", "minutes": 15}
            ]
        }
    }

    # ── CREATE THE EVENT ──────────────────────────────────────────────
    try:
        # insert() creates the event on the primary calendar
        # sendUpdates="all" sends email invites to all attendees
        created_event = calendar_service.events().insert(
            calendarId="primary",
            body=event,
            sendUpdates="all"   # Sends email invite to doctor automatically
        ).execute()

        print(f"[calendar] Appointment booked successfully!")
        print(f"[calendar] Event ID: {created_event.get('id')}")
        print(f"[calendar] Start: {start_iso}")
        print(f"[calendar] Doctor notified at: {doctor_email}")

        return created_event

    except Exception as e:
        print(f"[calendar] Failed to create calendar event: {e}")
        return None


if __name__ == "__main__":
    print("=" * 50)
    print("Testing Calendar Appointment Booking")
    print("=" * 50)

    # Use your own email as the doctor email for testing
    # Change this to your email before running
    TEST_DOCTOR_EMAIL = "rvdjahnavicheethirala@gmail.com"
    TEST_PATIENT_EMAIL = "harshinipenthala@gmail.com"
    TEST_PATIENT_NAME = "Test Patient"
    TEST_RISK_SUMMARY = "MEDIUM risk — Ear Infection"

    print(f"Booking test appointment...")
    print(f"Doctor email: {TEST_DOCTOR_EMAIL}")
    print(f"Patient: {TEST_PATIENT_NAME}")

    result = book_appointment(
        doctor_email=TEST_DOCTOR_EMAIL,
        patient_email=TEST_PATIENT_EMAIL,
        patient_name=TEST_PATIENT_NAME,
        risk_summary=TEST_RISK_SUMMARY
    )

    if result:
        print(f"\nTEST PASSED!")
        print(f"Event created: {result.get('summary')}")
        print(f"Event link: {result.get('htmlLink')}")
    else:
        print("\nTEST FAILED — check error messages above")

    print("=" * 50)