/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./hooks/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary":                    "#00342b",
        "on-primary":                 "#ffffff",
        "primary-container":          "#004d40",
        "on-primary-container":       "#7ebdac",
        "primary-fixed":              "#afefdd",
        "primary-fixed-dim":          "#94d3c1",
        "on-primary-fixed":           "#00201a",
        "on-primary-fixed-variant":   "#065043",
        "secondary":                  "#006876",
        "on-secondary":               "#ffffff",
        "secondary-container":        "#58e6ff",
        "on-secondary-container":     "#006573",
        "secondary-fixed":            "#a1efff",
        "secondary-fixed-dim":        "#44d8f1",
        "on-secondary-fixed":         "#001f25",
        "on-secondary-fixed-variant": "#004e59",
        "tertiary":                   "#20302f",
        "on-tertiary":                "#ffffff",
        "tertiary-container":         "#364646",
        "on-tertiary-container":      "#a2b3b3",
        "tertiary-fixed":             "#d4e6e5",
        "tertiary-fixed-dim":         "#b8cac9",
        "on-tertiary-fixed":          "#0e1e1e",
        "on-tertiary-fixed-variant":  "#3a4a49",
        "error":                      "#ba1a1a",
        "on-error":                   "#ffffff",
        "error-container":            "#ffdad6",
        "on-error-container":         "#93000a",
        "background":                 "#f7f9fb",
        "on-background":              "#191c1e",
        "surface":                    "#f7f9fb",
        "on-surface":                 "#191c1e",
        "surface-variant":            "#e0e3e5",
        "on-surface-variant":         "#3f4945",
        "outline":                    "#707975",
        "outline-variant":            "#bfc9c4",
        "surface-container-lowest":   "#ffffff",
        "surface-container-low":      "#f2f4f6",
        "surface-container":          "#eceef0",
        "surface-container-high":     "#e6e8ea",
        "surface-container-highest":  "#e0e3e5",
        "surface-dim":                "#d8dadc",
        "surface-bright":             "#f7f9fb",
        "surface-tint":               "#29695b",
        "inverse-surface":            "#2d3133",
        "inverse-on-surface":         "#eff1f3",
        "inverse-primary":            "#94d3c1",
      },
      spacing: {
        "xs":     "4px",
        "base":   "8px",
        "sm":     "12px",
        "md":     "24px",
        "gutter": "24px",
        "lg":     "48px",
        "xl":     "80px",
        "margin": "32px",
      },
      fontFamily: {
        manrope: ["var(--font-manrope)", "sans-serif"],
      },
      fontSize: {
        "caption":     ["12px",  { lineHeight: "1.2", fontWeight: "500" }],
        "label-md":    ["14px",  { lineHeight: "1.2", letterSpacing: "0.01em", fontWeight: "600" }],
        "body-md":     ["16px",  { lineHeight: "1.6", fontWeight: "400" }],
        "body-lg":     ["18px",  { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["24px",  { lineHeight: "1.4", fontWeight: "600" }],
        "headline-lg": ["32px",  { lineHeight: "1.3", fontWeight: "700" }],
        "display-xl":  ["48px",  { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "800" }],
      },
    },
  },
  plugins: [],
};
