# Generated by Django 6.0.4 on 2026-04-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorprofile",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="doctor_photos/"),
        ),
    ]
