# Generated by Django 6.0.1 on 2026-04-26 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="appointment",
            new_name="appointment_doctor__4efb5b_idx",
            old_name="appointmen_doctor_i_idx",
        ),
        migrations.RenameIndex(
            model_name="appointment",
            new_name="appointment_patient_f4324c_idx",
            old_name="appointmen_patient_idx",
        ),
    ]
