# Generated by Django 6.0 on 2026-04-26 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rehabplan',
            name='tasks',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
