# Generated by Django 6.0 on 2026-04-26 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehab', '0002_rehabplan_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisesession',
            name='body_part_scores',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
