# Generated by Django 6.0.4 on 2026-04-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("patient", "Patient"), ("doctor", "Doctor")],
                default="patient",
                max_length=10,
            ),
        ),
    ]
