#auth

@baseurl = http://localhost:3000/api

@doctormail = doctor@gmail.com
@doctorpassword = doctor@123


@patientmail = patient@gmail.com
@patientpassword = patient123


### Doctor login
POST {{baseurl}}/auth/doctor/login
Content-Type: application/json

{
    "email": "{{doctormail}}",
    "password": "{{doctorpassword}}"
}

### Patient login
POST {{baseurl}}/auth/patient/login
Content-Type: application/json

{
    "email": "{{patientmail}}",
    "password": "{{patientpassword}}"
}

### Patient signup
POST {{baseurl}}/auth/patient/signup
Content-Type: application/json

{
    "fullName": "Jane Doe",
    "email": "jane@example.com",
    "password": "password123"
}